// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRAhX06p8sU7nzNjdYIa0bKM6lqsuQFOc',
    appId: '1:1045454074577:web:24b04da18b2d9a2c340bf0',
    messagingSenderId: '1045454074577',
    projectId: 'myportfolio-472db',
    authDomain: 'myportfolio-472db.firebaseapp.com',
    storageBucket: 'myportfolio-472db.firebasestorage.app',
    measurementId: 'G-YYHGG84ZE0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClxnSUoBgC-Kshde4hbVPe74kmV3Z18HI',
    appId: '1:1045454074577:android:03bd9118ffbbafa6340bf0',
    messagingSenderId: '1045454074577',
    projectId: 'myportfolio-472db',
    storageBucket: 'myportfolio-472db.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlNTzUesIcmIf4XBat-VCHmahCynZj3Ug',
    appId: '1:1045454074577:ios:38fe1ac434831bbf340bf0',
    messagingSenderId: '1045454074577',
    projectId: 'myportfolio-472db',
    storageBucket: 'myportfolio-472db.firebasestorage.app',
    iosBundleId: 'com.example.flutterPortfolio',
  );
}
